### PR TITLE
Conflict

### PR DESCRIPTION
**Pull request by RichardLake**
Adding support for the UI to display conflicts. Depends on KSP-CKAN/CKAN-core#100. Tested on Windows. 
clipboard13

### CODE REVIEW

**Comment by pjf** [comment]
Just a quick note to say that I'm still reviewing this. Mostly I need to wrap my head around the changes in KSP-CKAN/CKAN-core#100.

**Comment by RichardLake** [comment]
Would close KSP-CKAN/CKAN#768

**Comment by mgsdk** [comment]
A possible issue with this, at least on Mono 3.12 and 4. Starting with a clean KSP 1.0.2 install and installing UniversalStorage 1.1.0.2 via the commandline, any attempt to upgrade it using the GUI  crashes CKAN.

The attempt to fix this via GUIMod:85
```
if ((bool)update_cell.Value != value)
```
makes the changeset tab appear after the update has been deselected, so the changeset tab shows up when there is no changes. Going to the changeset tab crashes the client.

Commenting out Main:468 does not seem to have any effect.

**Comment by pjf** [comment]
> Starting with a clean KSP 1.0.2 install and installing UniversalStorage 1.1.0.2 via the commandline, any attempt to upgrade it using the GUI crashes CKAN.

KSP-CKAN/CKAN#853 reported that US had a mispackaged file which we've since fixed. I'm going to try reproduce this now, but I'm wondering if we're seeing problems not because of this branch at all, but because installing broken mods is broken, and rather than suppressing the exception without logging it (which we'd do in the past), we're instead letting it fly.

However having the changetab cause the client to crash (without actually trying to run the changes) sure sounds like a problem. And users probably don't expect the whole GUI to fall over and die because a mod *did* have a file conflict, so we should probably have at least some exception handling to manage that.

**Comment by mgsdk** [comment]
To expand on this, I've tested with another mod and gotten the same results.

1. Starting with a clean KSP 1.0.2 install.
2. Update metadata (ckan.exe update)
3. Install SmartParts one version too old (ckan.exe install SmartParts=1.5.3)
4. Fire up the GUI, tick SmartParts for upgrade (Newest as of time of writing is 1.6.3).
5. Crash.

**Comment by pjf** [comment]
@mgsdk : Just to check, are you running KSP in between steps 1 and 3 somewhere, or is this all without running KSP at all?

**Comment by mgsdk** [comment]
No startup of KSP at any point.

**Comment by pjf** [comment]
Can reproduce under 3.2.8 (haven't tried others). This seems to repeat endless until it dies...

```
  at System.Windows.Forms.DataGridViewElement.RaiseCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x0002f>
  at System.Windows.Forms.DataGridViewCell.SetValue (int,object) <0x0021b>
  at System.Windows.Forms.DataGridViewCell.set_Value (object) <0x0002b>
  at CKAN.GUIMod.SetUpgradeChecked (System.Windows.Forms.DataGridViewRow,System.Nullable`1<bool>) <0x000df>
  at CKAN.Main.ModList_CellValueChanged (object,System.Windows.Forms.DataGridViewCellEventArgs) <0x00313>
  at System.Windows.Forms.DataGridView.OnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00069>
  at System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00020>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0xffffffff>
  at System.Windows.Forms.DataGridViewElement.RaiseCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x0002f>
  at System.Windows.Forms.DataGridViewCell.SetValue (int,object) <0x0021b>
  at System.Windows.Forms.DataGridViewCell.set_Value (object) <0x0002b>
  at CKAN.GUIMod.SetUpgradeChecked (System.Windows.Forms.DataGridViewRow,System.Nullable`1<bool>) <0x000df>
  at CKAN.Main.ModList_CellValueChanged (object,System.Windows.Forms.DataGridViewCellEventArgs) <0x00313>
  at System.Windows.Forms.DataGridView.OnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00069>
  at System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00020>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0xffffffff>
  at System.Windows.Forms.DataGridViewElement.RaiseCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x0002f>
  at System.Windows.Forms.DataGridViewCell.SetValue (int,object) <0x0021b>
  at System.Windows.Forms.DataGridViewCell.set_Value (object) <0x0002b>
  at CKAN.GUIMod.SetUpgradeChecked (System.Windows.Forms.DataGridViewRow,System.Nullable`1<bool>) <0x000df>
  at CKAN.Main.ModList_CellValueChanged (object,System.Windows.Forms.DataGridViewCellEventArgs) <0x00313>
  at System.Windows.Forms.DataGridView.OnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00069>
  at System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00020>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0xffffffff>
  at System.Windows.Forms.DataGridViewElement.RaiseCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x0002f>
  at System.Windows.Forms.DataGridViewCell.SetValue (int,object) <0x0021b>
  at System.Windows.Forms.DataGridViewCell.set_Value (object) <0x0002b>
  at CKAN.GUIMod.SetUpgradeChecked (System.Windows.Forms.DataGridViewRow,System.Nullable`1<bool>) <0x000df>
  at CKAN.Main.ModList_CellValueChanged (object,System.Windows.Forms.DataGridViewCellEventArgs) <0x00313>
  at System.Windows.Forms.DataGridView.OnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00069>
  at System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00020>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0xffffffff>
  at System.Windows.Forms.DataGridViewElement.RaiseCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x0002f>
  at System.Windows.Forms.DataGridViewCell.SetValue (int,object) <0x0021b>
  at System.Windows.Forms.DataGridViewCell.set_Value (object) <0x0002b>
  at CKAN.GUIMod.SetUpgradeChecked (System.Windows.Forms.DataGridViewRow,System.Nullable`1<bool>) <0x000df>
  at CKAN.Main.ModList_CellValueChanged (object,System.Windows.Forms.DataGridViewCellEventArgs) <0x00313>
  at System.Windows.Forms.DataGridView.OnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00069>
  at System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00020>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0xffffffff>
```

**Comment by mgsdk** [comment]
No issues on Mono 3.12.1 and Mono 4.0.1.28 after the latest fix.

**Comment by pjf** [comment]
Works for me under mono 3.2.8. :)

**Comment by pjf** [comment]
Merging with great joy. Thank you! :)

**Pull request merged**
