### PR TITLE
Seems to fix issues on mono 4 without negatively effecting Windows.

### PR DESCRIPTION
**Pull request by RichardLake**
Thanks to mgsdk for isolating the error.

### CODE REVIEW

**Comment by RichardLake** [comment]
Needs testing on linux with both mono 3.x and mono 4.x

**Comment by mgsdk** [comment]
Testing procedure: Select Ambient Light Adjustment and AntennaRange. Make sure they are not cached. Install, check they are in the KSP GameData folder, uninstall.

On Arch Linux:
Mono 3.12.1: Works.
Mono 4.0.1: Works.

**Comment by RichardLake** [comment]
Should close :
KSP-CKAN/CKAN#808
KSP-CKAN/CKAN-support#127

**Comment by mgsdk** [comment]
Might also close:
https://github.com/KSP-CKAN/CKAN-GUI/issues/76

**Pull request merged**
