### PR TITLE
OS X App Bundle

### PR DESCRIPTION
**Pull request by alampros**
I added a separate build script for creating a Mac OS X application bundle (double-clickable executable in OS X) with the requisite mac icon file (`.icns`). I'm not entirely certain this is the correct way to do it, but based on the very [limited documentation](http://www.mono-project.com/archived/guiderunning_mono_applications/#macpack-mac-os-x-only) from Xamarin, I was able to get it working.

I put the resultant bundle [up on dropbox](https://www.dropbox.com/s/84j6nwtmjkka3qy/CKAN.app.zip?dl=0) for testing. OS X users will still have to install the mono framework [as described in the wiki](https://github.com/KSP-CKAN/CKAN-support/wiki/Installing-CKAN-on-OSX).

**update:** [Here's a build with the v1.6.0 core](https://www.dropbox.com/s/mqih53gy08nfpqy/CKAN.app_v1.6.0.zip?dl=0).

I would love to see this package added to the releases on the main repo sometime.

### CODE REVIEW

**Comment by Ippo343** [comment]
Hey @alampros , I have neither a Mac nor time to review this right now, but I wanted to thank you immediately! You are awesome!

**Comment by hakan42** [comment]
@alampros thank you for the contribution, I would add this to our buildchain for the GUI as soon as Jenkins is alive again

**Comment by alampros** [comment]
You're very welcome! But don't thank me yet...until someone else tests it. :grin:

**Comment by alampros** [comment]
@hakan42 what's going on with jenkins?

**Comment by hakan42** [comment]
@alampros basically, the box periodically runs out of disc space, killing Jenkins along the way. Connect this with the Docker process leaking something and failing to start new slaves after some time, we have a build server that needs periodic hand holding...

**Pull request merged**
